root: true
extends:
  - 'eslint:recommended'
env:
  browser: true
  es2021: true
  node: true
overrides:
  - files:
    - "**/*.ts"
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/recommended
    overrides: []
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: latest
      sourceType: module
    plugins:
      - '@typescript-eslint'
    rules: {}
